FILE.exe: stack_main.o stack.o
    gcc -o FILE.exe stack.o stack_main.o -Wall
stack.o: stack.c stack.h
    gcc -c -g stack.c -Wall
stack_main.o : stack_main.c stack.h
    gcc -c -g stack_main.c -Wall